import {
    PROFILE_READ,
    PROFILE_UPDATE,
    PROFILE_DELETE,
    MESSAGE_CREATE,
    MESSAGE_READ,
    MESSAGE_UPDATE,
    MESSAGE_DELETE,
    CONVERSATION_CREATE,
    CONVERSATION_READ,
    CONVERSATION_UPDATE,
    CONVERSATION_DELETE,
    RESOURCE_CREATE,
    RESOURCE_READ,
    RESOURCE_UPDATE,
    RESOURCE_DELETE,
    SYSTEM_MANAGE,
} from './permissions.constants';

export const ROLE_USER =
    PROFILE_READ |
    PROFILE_UPDATE |
    MESSAGE_CREATE |
    MESSAGE_READ |
    MESSAGE_UPDATE |
    MESSAGE_DELETE |
    CONVERSATION_CREATE |
    CONVERSATION_READ |
    CONVERSATION_UPDATE |
    CONVERSATION_DELETE |
    RESOURCE_CREATE |
    RESOURCE_READ |
    RESOURCE_UPDATE |
    RESOURCE_DELETE;

export const ROLE_ADMIN =
    ROLE_USER | PROFILE_DELETE | SYSTEM_MANAGE;
